### ISSUE TITLE
Plasma crack?

### ISSUE THREAD

**Issue by teleportingtortoise** [ChrisMiuchiz/Plasma-Graphics-File-Parser#1]
Sorry, this is only partly related to this project. I was wondering if you have any plans to crack Plasma.

**Comment by coremaze** [comment]
Only a few people have a copy of the program which Wollay released in like 2011 or 2012. I believe it required a license key and access to an authentication server in order to create or modify files, which no longer exists. Yes, I think it would be trivial for me to crack Plasma, but no one who has the program is willing to distribute it.

**Comment by teleportingtortoise** [comment]
How could I get the installer to you?

**Comment by coremaze** [comment]
If you have a copy of Plasma, you could contact me via email at ChrisMiuchiz@gmail.com

**Comment by coremaze** [comment]
@teleportingtortoise Hey, are you still around? Development on this is well underway, but you haven't responded to my emails in a while. I'm looking for some data that you still may have.
